name: publish

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version-file: "package.json"

    - name: Setup pnpm
      uses: pnpm/action-setup@v3

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile

    - name: Build Declarations
      id: build
      env:
        MAKEFILE_BUILD_FORCE: ${{github.event_name == 'workflow_dispatch'}}
      run: |
        s=$(pnpm build)
        echo "stdout<<EOF" >> "$GITHUB_OUTPUT"
        echo "$s" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

    - name: Setup Git
      if: ${{!contains(steps.build.outputs.stdout, 'no updates')}}
      run: |
        re=$(curl --silent --header "Accept: application/json" "https://api.github.com/users/github-actions%5Bbot%5D")
        lo=$(echo "$re" | jq --raw-output ".login")
        id=$(echo "$re" | jq --raw-output ".id")
        git config --global user.name "$lo"
        git config --global user.email "$id+$lo@users.noreply.github.com"

    - name: Publish Declarations
      if: ${{!contains(steps.build.outputs.stdout, 'no updates')}}
      working-directory: dist
      run: |
        un=$(git config --get user.name)
        ru="${{github.server_url}}/${{github.repository}}.git"
        ru=$(echo "$ru" | sed "s#https://#https://$un:${{github.token}}@#")

        td=$(mktemp -d)
        git clone --quiet --no-checkout --single-branch --branch dist "$ru" "$td"

        mv "$td/.git" .
        git add .

        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit --quiet --message "$(date --utc)"
          git push
        fi
